included: # paths to include during linting. `--path` is ignored if present.
  - SwiftIOSExperiments
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods